Repository bean-space/bean-space-front, pull requests merged in 2024-07, with the labels that each got.

#3 ✨ Header 구현
  .eslintrc.cjs
  index.html
  src/App.jsx
  src/api/auth.js
  src/api/client.js
  src/assets/kakao_login_large_wide.png
  src/components/Header.jsx
  src/components/LoginContainer.jsx
  src/components/MainCards.jsx
  src/components/SignupContainer.jsx
  src/components/SpaceCard.jsx
  src/context/AuthContext.jsx
  src/hooks/useAuth.js
  src/main.jsx
  src/pages/LoginPage.jsx
  src/pages/MainPage.jsx
  src/pages/SignupPage.jsx
Labels: enhancement, front

#6 ✨ 회원가입 페이지 구현
  package-lock.json
  package.json
  src/api/auth.js
  src/api/image.js
  src/assets/kakao-logo.png
  src/assets/kakao_login_large_wide.png
  src/components/AuthCallback.jsx
  src/components/LoginContainer.jsx
  src/components/SignupContainer.jsx
Labels: enhancement, front

#8 ✨ 공간 검색 기능 구현
  package-lock.json
  package.json
  src/App.jsx
  src/api/space.js
  src/assets/coupon_banner.png
  src/assets/default_house_pic.jpg
  src/assets/default_profile_image.webp
  src/components/DateRangePicker.jsx
  src/components/Header.jsx
  src/components/LoginContainer.jsx
  src/components/MainCards.jsx
  src/components/PeopleCountDropdown.jsx
  src/components/SearchBar.jsx
  src/components/SearchInput.jsx
  src/components/SidoDropdown.jsx
  src/components/SignupContainer.jsx
  src/components/SpaceCardList.jsx
  src/components/SpaceDetailContainer.jsx
  src/main.jsx
  src/pages/MainPage.jsx
  src/pages/SearchResultPage.jsx
  src/pages/SpaceDetailPage.jsx
Labels: enhancement

#15 ✨ 예약 페이지 구현
  src/App.jsx
  src/api/coupon.js
  src/api/reservation.js
  src/components/Header.jsx
  src/components/LoginContainer.jsx
  src/components/MyReservationContainer.jsx
  src/components/ReservationContainer.jsx
  src/components/SearchBar.jsx
  src/components/SpaceDetailContainer.jsx
  src/pages/MyReservationPage.jsx
  src/pages/ReservationPage.jsx
Labels: enhancement, front

#18 🗑️ 불필요한 파일 제거
  src/components/CouponContainer.jsx
Labels: front

#19 ✨쿠폰 발급 페이지 구현
  src/App.jsx
  src/api/coupon.js
  src/api/todos.js
  src/components/CouponContainer.jsx
Labels: enhancement, front
